
"use client";

import React, { useEffect, useState } from "react";
import {
  AnimatePresence,
  motion,
  useMotionValue,
  useSpring,
  useTransform,
  Variants,
} from "framer-motion";

import "./about.css";
import SiteFooter from "@/components/site-footer"
import Impact from "@/components/impact"
import ImaggeViewer from "@/components/View";
import ContactForm from "@/components/contactform";
import SiteNavbar from "@/components/site-navbar";

interface StrategicItem {
  id: string;
  icon: string;
  title: string;
  description: string;
}

const strategicItems: StrategicItem[] = [
  {
    id: "01",
    icon: "/assets/icons/icons3/i1.svg",
    title: "Ground Reality & Intelligence",
    description:
      "We gather real inputs from the ground — public sentiment, local concerns, community priorities, organisational signals, and field-level feedback. This helps ensure every strategic decision begins with reality, evidence, and a clear understanding of what people are experiencing.",
  },
  {
    id: "02",
    icon: "/assets/icons/icons3/i2.svg",
    title: "Structured Analysis & Validation",
    description:
      "Every field input is reviewed and interpreted by our research team, analysts, and specialists through structured methods. This helps reveal important patterns, emerging risks, and areas that require focused attention.",
  },
  {
    id: "03",
    icon: "/assets/icons/icons3/i3.svg",
    title: "Action Planning & Strategic Direction",
    description:
      "Using these findings, we establish a practical direction — where attention is needed, what should come first, and which actions can create meaningful results. The objective is to connect strategy with realities on the ground for stronger outcomes.",
  },
  {
    id: "04",
    icon: "/assets/icons/icons3/i4.svg",
    title: "Action Planning & Strategic Direction",
    description:
      "Using these findings, we establish a practical direction — where attention is needed, what should come first, and which actions can create meaningful results. The objective is to connect strategy with realities on the ground for stronger outcomes.",
  },
  {
    id: "05",
    icon: "/assets/icons/icons3/i5.svg",
    title: "Continuous Tracking & Improvement",
    description:
      "We continuously observe developments on the ground, changing public concerns, and the response generated by ongoing actions. This allows timely adjustments, sharper decisions, and stronger control over the direction and outcomes.",
  },
];

/* =========================================================
   FRAMER MOTION VARIANTS
   ========================================================= */

const fadeUp: Variants = {
  hidden: {
    opacity: 0,
    y: 55,
  },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.8,
      ease: [0.22, 1, 0.36, 1],
    },
  },
};

const fadeUpSoft: Variants = {
  hidden: {
    opacity: 0,
    y: 30,
  },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.7,
      ease: [0.22, 1, 0.36, 1],
    },
  },
};

const strategicContainer: Variants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.13,
      delayChildren: 0.05,
    },
  },
};

const strategicItem: Variants = {
  hidden: {
    opacity: 0,
    y: 55,
    scale: 0.97,
  },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: {
      duration: 0.75,
      ease: [0.22, 1, 0.36, 1],
    },
  },
};

const lifeContainer: Variants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.12,
      delayChildren: 0.05,
    },
  },
};

const imageReveal: Variants = {
  hidden: {
    opacity: 0,
    y: 55,
    scale: 0.96,
  },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: {
      duration: 0.85,
      ease: [0.22, 1, 0.36, 1],
    },
  },
};

const modalOverlay: Variants = {
  hidden: {
    opacity: 0,
  },
  visible: {
    opacity: 1,
    transition: {
      duration: 0.25,
      ease: "easeOut",
    },
  },
  exit: {
    opacity: 0,
    transition: {
      duration: 0.2,
      ease: "easeIn",
    },
  },
};

const modalContent: Variants = {
  hidden: {
    opacity: 0,
    y: 35,
    scale: 0.94,
  },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: {
      duration: 0.4,
      ease: [0.22, 1, 0.36, 1],
    },
  },
  exit: {
    opacity: 0,
    y: 25,
    scale: 0.96,
    transition: {
      duration: 0.25,
      ease: [0.4, 0, 1, 1],
    },
  },
};

/* =========================================================
   ABOUT INTRO / INDIA TROLL
   ========================================================= */

const AboutIntroSection = () => {
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);

  const rotateY = useSpring(
    useTransform(mouseX, [-0.5, 0.5], [-12, 12]),
    { stiffness: 180, damping: 22, mass: 0.7 }
  );

  const rotateX = useSpring(
    useTransform(mouseY, [-0.5, 0.5], [10, -10]),
    { stiffness: 180, damping: 22, mass: 0.7 }
  );

  const handleMouseMove = (event: React.MouseEvent<HTMLDivElement>) => {
    const rect = event.currentTarget.getBoundingClientRect();
    const x = (event.clientX - rect.left) / rect.width - 0.5;
    const y = (event.clientY - rect.top) / rect.height - 0.5;

    mouseX.set(x);
    mouseY.set(y);
  };

  const handleMouseLeave = () => {
    mouseX.set(0);
    mouseY.set(0);
  };

  return (
    <motion.section
      className="about-who-we-are-section"
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, amount: 0.15 }}
    >
      <div className="about-who-we-are-container">
        <motion.div
          className="about-who-we-are-visual"
          initial={{ opacity: 0, x: -45, scale: 0.94 }}
          whileInView={{ opacity: 1, x: 0, scale: 1 }}
          viewport={{ once: true, amount: 0.25 }}
          transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
          style={{ perspective: 1200 }}
        >
          <motion.div
            className="about-who-we-are-map-wrap"
            onMouseMove={handleMouseMove}
            onMouseLeave={handleMouseLeave}
            style={{
              rotateX,
              rotateY,
              transformStyle: "preserve-3d",
            }}
            whileHover={{ scale: 1.025 }}
            transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
          >
            <motion.img
              src="/assets/india-map-analytics.png"
              alt="India map analytics illustration"
              className="about-who-we-are-map"
              style={{ z: 28 }}
              draggable={false}
            />
          </motion.div>
        </motion.div>

        <motion.div
          className="about-who-we-are-content"
          initial={{ opacity: 0, x: 45 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.25 }}
          transition={{
            duration: 0.85,
            delay: 0.12,
            ease: [0.22, 1, 0.36, 1],
          }}
        >
          <motion.div
            className="about-who-we-are-label"
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            ABOUT INDIA TROLL
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 25 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{
              duration: 0.7,
              delay: 0.08,
              ease: [0.22, 1, 0.36, 1],
            }}
          >
            WHO WE ARE
          </motion.h1>

          <motion.div
            className="about-who-we-are-line"
            initial={{ scaleX: 0, opacity: 0 }}
            whileInView={{ scaleX: 1, opacity: 1 }}
            viewport={{ once: true }}
            transition={{
              duration: 0.65,
              delay: 0.2,
              ease: [0.22, 1, 0.36, 1],
            }}
          />

          <div className="about-who-we-are-copy">
            <p>
              India Troll is a research, strategy, and execution-focused organisation
              working across India with a strong focus on understanding public
              opinion, political environments, and changing ground realities.
            </p>

            <p>
              We work with political leaders, organisations, institutions, and teams that
              need a clear understanding of public sentiment and changing realities.
              Our focus is to study what is happening on the ground and convert
              those observations into clear, practical inputs that support
              planning, communication, decision-making, and execution. Through
              election research, public opinion studies, and strategic assignments,
              India Troll brings structured research and grounded insights together
              to help teams make informed decisions in complex environments.
            </p>

            <p>
              Our strength lies in combining field intelligence with structured
              research and data analysis to understand public behaviour and changing
              sentiment. Our work is guided by evidence gathered from the field,
              supported by careful interpretation, and focused on turning information
              into insights that can be understood, evaluated, and acted upon.
            </p>

            <p>
              Our work is rooted in political research and campaign intelligence —
              covering surveys, public sentiment, and constituency-level insights
              that help shape election strategy. Over time, our approach has grown
              to include wider research and strategic support, helping organisations
              monitor developments, identify gaps, understand local priorities,
              and strengthen the way decisions are planned and executed.
            </p>
          </div>
        </motion.div>
      </div>
    </motion.section>
  );
};

/* =========================================================
   OUR CARD COMPONENT
   ========================================================= */

interface StrategicCardProps {
  item: StrategicItem;
}

const StrategicCard = ({ item }: StrategicCardProps) => {
  return (
    <motion.div
      className={`strategic-item strategic-item-${item.id}`}
      variants={strategicItem}
      whileHover="hover"
    >
      {/* ICON */}
      <motion.div
        className="strategic-icon-wrapper"
        variants={{
          hidden: {
            opacity: 0,
            scale: 0.7,
            rotate: -8,
          },
          visible: {
            opacity: 1,
            scale: 1,
            rotate: 0,
            transition: {
              duration: 0.65,
              ease: [0.22, 1, 0.36, 1],
            },
          },
        }}
      >
        <motion.div
          className="strategic-icon-circle"
          variants={{
            hover: {
              scale: 1.08,
              backgroundColor: "var(--brand-gold)",
              boxShadow: "0 14px 35px rgba(245, 181, 35, 0.24)",
              transition: {
                duration: 0.3,
                ease: "easeOut",
              },
            },
          }}
        >
          <motion.img
            src={item.icon}
            alt=""
            className="strategic-icon"
            variants={{
              hover: {
                scale: 1.08,
                rotate: 3,
                transition: {
                  duration: 0.3,
                  ease: "easeOut",
                },
              },
            }}
          />
        </motion.div>
      </motion.div>

      {/* NUMBER */}
      <div className="strategic-number">
        <motion.span
          className="strategic-number-value"
          whileHover={{
            scale: 1.08,
            transition: {
              duration: 0.25,
            },
          }}
        >
          {item.id}
        </motion.span>
      </div>

      {/* CARD */}
      <motion.div
        className="strategic-card"
        variants={{
          hover: {
            y: -7,
            boxShadow: "0 24px 48px rgba(0, 0, 0, 0.13)",
            transition: {
              duration: 0.35,
              ease: [0.22, 1, 0.36, 1],
            },
          },
        }}
      >
        <h3>{item.title}</h3>

        <p>{item.description}</p>
      </motion.div>
    </motion.div>
  );
};

/* =========================================================
   CURVED ARROW COMPONENT
   ========================================================= */

const StrategicArrow = ({
  className,
}: {
  className: string;
}) => {
  return (
    <motion.div
      className={`strategic-arrow ${className}`}
      initial={{
        opacity: 0,
        scale: 0.7,
      }}
      whileInView={{
        opacity: 1,
        scale: 1,
      }}
      viewport={{
        once: true,
        amount: 0.4,
      }}
      transition={{
        duration: 0.7,
        ease: [0.22, 1, 0.36, 1],
        delay: 0.3,
      }}
    >
      {/* Exact 230 × 115 SVG exported from the supplied Fabric.js artwork */}
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        version="1.1"
        width="230"
        height="115"
        viewBox="0 0 230 115"
        xmlSpace="preserve"
        aria-hidden="true"
        focusable="false"
      >
        <desc>Created with Fabric.js 6.5.3</desc>

        <defs />

        <g transform="matrix(1 0 0 1 107.4437 40.84)">
          <path
            style={{
              stroke: "rgb(255,184,28)",
              strokeWidth: 3.5,
              strokeDasharray: "none",
              strokeLinecap: "round",
              strokeDashoffset: 0,
              strokeLinejoin: "round",
              strokeMiterlimit: 4,
              fill: "none",
              fillRule: "nonzero",
              opacity: 1,
            }}
            transform="translate(-87 -40.9334)"
            d="M 5 58 C 55 8 125 8 169 61"
            stroke="rgb(255,184,28)"
            strokeLinecap="round"
          />
        </g>

        <g transform="matrix(0.7459 0.6854 -0.6854 0.7459 187.7622 57.7277)">
          <path
            style={{
              stroke: "rgb(255,184,28)",
              strokeWidth: 3.5,
              strokeDasharray: "none",
              strokeLinecap: "round",
              strokeDashoffset: 0,
              strokeLinejoin: "round",
              strokeMiterlimit: 4,
              fill: "none",
              fillRule: "nonzero",
              opacity: 1,
            }}
            transform="translate(-161.5 -59)"
            d="M 169 61 L 155 51 M 169 61 L 154 67"
            stroke="rgb(255,184,28)"
            strokeLinecap="round"
          />
        </g>
      </svg>
    </motion.div>
  );
};

/* =========================================================
   LIFE IMAGE COMPONENT
   ========================================================= */

interface LifeImageProps {
  src: string;
  alt: string;
  className: string;
}

const LifeImage = ({
  src,
  alt,
  className,
}: LifeImageProps) => {
  return (
    <motion.div
      className={`life-rudra-image-card ${className}`}
      variants={imageReveal}
      whileHover={{
        y: -8,
        boxShadow: "0 20px 42px rgba(0, 0, 0, 0.38)",
        transition: {
          duration: 0.35,
          ease: [0.22, 1, 0.36, 1],
        },
      }}
    >
      <motion.img
        src={src}
        alt={alt}
        className="life-rudra-image"
        initial={{
          scale: 1.08,
        }}
        whileInView={{
          scale: 1,
        }}
        viewport={{
          once: true,
          amount: 0.2,
        }}
        whileHover={{
          scale: 1.055,
          transition: {
            duration: 0.65,
            ease: [0.22, 1, 0.36, 1],
          },
        }}
        transition={{
          duration: 1,
          ease: [0.22, 1, 0.36, 1],
        }}
      />
    </motion.div>
  );
};

/* =========================================================
   PAGE
   ========================================================= */

const Page = () => {
  const [isContactModalOpen, setIsContactModalOpen] =
    useState(false);

  const openContactModal = () => {
    setIsContactModalOpen(true);
  };

  const closeContactModal = () => {
    setIsContactModalOpen(false);
  };

  /* =========================================================
     PREVENT BACKGROUND SCROLL WHEN MODAL IS OPEN
     ========================================================= */

  useEffect(() => {
    const previousBodyOverflow = document.body.style.overflow;
    const previousBodyOverflowX = document.body.style.overflowX;
    const previousHtmlOverflowX = document.documentElement.style.overflowX;

    if (isContactModalOpen) {
      document.body.style.overflow = "hidden";
      document.body.style.overflowX = "hidden";
      document.documentElement.style.overflowX = "hidden";
    } else {
      document.body.style.overflow = "";
      document.body.style.overflowX = "";
      document.documentElement.style.overflowX = "";
    }

    return () => {
      document.body.style.overflow = previousBodyOverflow;
      document.body.style.overflowX = previousBodyOverflowX;
      document.documentElement.style.overflowX = previousHtmlOverflowX;
    };
  }, [isContactModalOpen]);

  /* =========================================================
     ESCAPE KEY
     ========================================================= */

  useEffect(() => {
    if (!isContactModalOpen) {
      return;
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        closeContactModal();
      }
    };

    document.addEventListener(
      "keydown",
      handleEscape
    );

    return () => {
      document.removeEventListener(
        "keydown",
        handleEscape
      );
    };
  }, [isContactModalOpen]);

  return (
    <>
      <SiteNavbar />

      {/* =====================================================
          WHO WE ARE / ABOUT INTRO SECTION
          ===================================================== */}

      <AboutIntroSection />

      {/* =====================================================
          RESEARCH PLATFORM SECTION
          ===================================================== */}

      <motion.section
        className="about-app-section"
        initial="hidden"
        whileInView="visible"
        viewport={{
          once: true,
          amount: 0.2,
          margin: "0px 0px -50px 0px",
        }}
      >
        <div className="about-app-container">
          {/* HAND / PHONE */}
<Impact/>
          <motion.div
            className="about-hand-reveal"
            variants={{
              hidden: {
                opacity: 0,
                y: 45,
                scale: 0.92,
              },
              visible: {
                opacity: 1,
                y: 0,
                scale: 1,
                transition: {
                  duration: 0.9,
                  ease: [0.22, 1, 0.36, 1],
                },
              },
            }}
          >
            <motion.div
              className="about-hand-float"
              animate={{
                y: [-5, 5, -5],
              }}
              transition={{
                duration: 3.5,
                ease: "easeInOut",
                repeat: Infinity,
              }}
            >
              <motion.img
                src="/hands1.png"
                alt="Hand holding phone"
                className="about-hand-image"
                initial={{
                  rotate: -3,
                }}
                whileInView={{
                  rotate: 0,
                }}
                viewport={{
                  once: true,
                }}
                transition={{
                  duration: 0.9,
                  ease: [0.22, 1, 0.36, 1],
                }}
              />
            </motion.div>
          </motion.div>

          {/* TEXT */}

          <motion.div
            className="about-app-text"
            variants={{
              hidden: {
                opacity: 0,
                y: 35,
              },
              visible: {
                opacity: 1,
                y: 0,
                transition: {
                  duration: 0.8,
                  delay: 0.2,
                  ease: [0.22, 1, 0.36, 1],
                },
              },
            }}
          >
            <motion.p>
              Our research team uses a{" "}
              <motion.span
                initial={{
                  opacity: 0,
                  x: 15,
                }}
                whileInView={{
                  opacity: 1,
                  x: 0,
                }}
                viewport={{
                  once: true,
                }}
                transition={{
                  duration: 0.6,
                  delay: 0.4,
                }}
              >
                Dedicated Research Platform
              </motion.span>
            </motion.p>

            <p>
              to conduct structured, unbiased, and accurate surveys.
            </p>
          </motion.div>
        </div>
      </motion.section>

      {/* =====================================================
          OUR APPROACH SECTION
          ===================================================== */}

      <motion.section
        className="strategic-approach-section"
        initial="hidden"
        whileInView="visible"
        viewport={{
          once: true,
          amount: 0.08,
          margin: "0px 0px -60px 0px",
        }}
      >
        <div className="strategic-approach-container">
          {/* HEADING */}

          <motion.div
            className="strategic-heading"
            variants={fadeUp}
          >
            <motion.div
              className="strategic-small-title"
              initial={{
                opacity: 0,
                y: 15,
              }}
              whileInView={{
                opacity: 1,
                y: 0,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.5,
              }}
            >
              OUR
            </motion.div>

            <motion.h2
              initial={{
                opacity: 0,
                y: 20,
              }}
              whileInView={{
                opacity: 1,
                y: 0,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.65,
                delay: 0.1,
                ease: [0.22, 1, 0.36, 1],
              }}
            >
              APPROACH
            </motion.h2>

            <motion.div
              className="strategic-heading-line"
              initial={{
                scaleX: 0,
                opacity: 0,
              }}
              whileInView={{
                scaleX: 1,
                opacity: 1,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.65,
                delay: 0.25,
                ease: [0.22, 1, 0.36, 1],
              }}
            />

            <motion.p
              initial={{
                opacity: 0,
                y: 20,
              }}
              whileInView={{
                opacity: 1,
                y: 0,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.7,
                delay: 0.3,
                ease: [0.22, 1, 0.36, 1],
              }}
            >
              Our approach is built around ground reality, evidence, and practical
              decision-making. We focus on understanding what is
              changing across communities and converting those findings
              into clear direction, priorities, and actionable strategy.
            </motion.p>
          </motion.div>

          {/* =================================================
              FIRST ROW
              ================================================= */}

          <motion.div
            className="strategic-timeline-row strategic-row-one"
            variants={strategicContainer}
          >
            {/* HORIZONTAL LINE */}

            <motion.div
              className="strategic-horizontal-line"
              initial={{
                scaleX: 0,
                transformOrigin: "left",
              }}
              whileInView={{
                scaleX: 1,
              }}
              viewport={{
                once: true,
                amount: 0.3,
              }}
              transition={{
                duration: 1.2,
                ease: [0.22, 1, 0.36, 1],
                delay: 0.2,
              }}
            >
              <motion.span
                className="line-dot line-dot-left"
                initial={{
                  scale: 0,
                  opacity: 0,
                }}
                whileInView={{
                  scale: 1,
                  opacity: 1,
                }}
                viewport={{
                  once: true,
                }}
                transition={{
                  duration: 0.4,
                  delay: 0.9,
                }}
              />

              <motion.span
                className="line-dot line-dot-right"
                initial={{
                  scale: 0,
                  opacity: 0,
                }}
                whileInView={{
                  scale: 1,
                  opacity: 1,
                }}
                viewport={{
                  once: true,
                }}
                transition={{
                  duration: 0.4,
                  delay: 1.1,
                }}
              />
            </motion.div>

            {/* ARROW 01 → 02 */}

            <StrategicArrow className="strategic-arrow-one" />

            {/* ARROW 02 → 03 */}

            <StrategicArrow className="strategic-arrow-two" />

            {/* ITEMS */}

            <StrategicCard item={strategicItems[0]} />

            <StrategicCard item={strategicItems[1]} />

            <StrategicCard item={strategicItems[2]} />
          </motion.div>

          {/* =================================================
              SECOND ROW
              ================================================= */}

          <motion.div
            className="strategic-timeline-row strategic-row-two"
            variants={strategicContainer}
          >
            {/* HORIZONTAL LINE */}

            <motion.div
              className="strategic-horizontal-line"
              initial={{
                scaleX: 0,
                transformOrigin: "left",
              }}
              whileInView={{
                scaleX: 1,
              }}
              viewport={{
                once: true,
                amount: 0.3,
              }}
              transition={{
                duration: 1,
                ease: [0.22, 1, 0.36, 1],
                delay: 0.15,
              }}
            >
              <span className="line-dot line-dot-left" />
              <span className="line-dot line-dot-right" />
            </motion.div>

            {/* ARROW 04 → 05 */}

            <StrategicArrow className="strategic-arrow-three" />

            {/* ITEMS */}

            <StrategicCard item={strategicItems[3]} />

            <StrategicCard item={strategicItems[4]} />
          </motion.div>
        </div>
      </motion.section>

      {/* =====================================================
          LIFE @ INDIA TROLL
          ===================================================== */}

      <motion.section
        className="life-rudra-section"
        initial="hidden"
        whileInView="visible"
        viewport={{
          once: true,
          amount: 0.08,
          margin: "0px 0px -80px 0px",
        }}
      >
        <motion.div
          className="life-rudra-container"
          variants={lifeContainer}
        >
          {/* HEADER */}

          <motion.div
            className="life-rudra-header life-rudra-reveal"
            variants={fadeUp}
          >
            <motion.div
              className="life-rudra-label"
              initial={{
                opacity: 0,
                x: -25,
              }}
              whileInView={{
                opacity: 1,
                x: 0,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.6,
              }}
            >
              Life@India Troll
            </motion.div>

            <motion.h2
              initial={{
                opacity: 0,
                y: 25,
              }}
              whileInView={{
                opacity: 1,
                y: 0,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.8,
                delay: 0.1,
                ease: [0.22, 1, 0.36, 1],
              }}
            >
              Built around people, ideas, and purpose.
            </motion.h2>

            <motion.div
              className="life-rudra-heading-line"
              initial={{
                scaleX: 0,
                transformOrigin: "left",
              }}
              whileInView={{
                scaleX: 1,
              }}
              viewport={{
                once: true,
              }}
              transition={{
                duration: 0.7,
                delay: 0.3,
              }}
            />
          </motion.div>

          {/* DESCRIPTION */}

          <motion.div
            className="life-rudra-description life-rudra-reveal"
            variants={fadeUpSoft}
          >
            <p>
              We believe strong work begins with respect for one
              another. Our best outcomes come from collaboration,
              openness, and a shared commitment to doing meaningful work.
              We stay focused on the purpose behind what we do,
              while creating space to learn, grow, celebrate progress,
              recognise contributions, and build genuine human connections
              across the people who make India Troll what it is.
            </p>
          </motion.div>

          {/* IMAGE GALLERY */}

          <ImaggeViewer>
            <motion.div
              className="life-rudra-gallery"
              variants={lifeContainer}
            >
              <LifeImage
                src="/assets/ImgForAbout/Img1.jpeg"
                alt="India Troll team gathering"
                className="life-rudra-image-card-1"
              />

              <LifeImage
                src="/assets/ImgForAbout/Img2.jpeg"
                alt="India Troll team activity"
                className="life-rudra-image-card-2"
              />

              <LifeImage
                src="/assets/ImgForAbout/Img3.jpeg"
                alt="India Troll team celebration"
                className="life-rudra-image-card-3"
              />
            </motion.div>
          </ImaggeViewer>

          {/* CTA */}

          <motion.div
            className="life-rudra-cta-area"
            variants={lifeContainer}
          >
            {/* PARTNER */}

            <motion.div
              className="life-rudra-cta life-rudra-cta-left"
              variants={fadeUp}
            >
              <motion.h3 variants={fadeUpSoft}>
                Partner with us
              </motion.h3>

              <motion.button
                type="button"
                className="life-rudra-touch-button"
                aria-label="Get in touch for partnership"
                onClick={openContactModal}
                whileHover={{
                  y: -5,
                  scale: 1.02,
                  backgroundColor: "var(--brand-gold)",
                  color: "var(--site-bg)",
                  boxShadow:
                    "0 14px 32px rgba(245, 181, 35, 0.2)",
                  transition: {
                    duration: 0.25,
                  },
                }}
                whileTap={{
                  scale: 0.97,
                  y: 0,
                }}
              >
                <motion.span
                  className="life-rudra-button-arrow"
                  whileHover={{
                    x: 6,
                  }}
                >
                  →
                </motion.span>

                <span>Get in touch</span>
              </motion.button>
            </motion.div>

            {/* JOIN */}

            <motion.div
              className="life-rudra-cta life-rudra-cta-right"
              variants={fadeUp}
            >
              <motion.h3 variants={fadeUpSoft}>
                Join our team
              </motion.h3>

              <motion.button
                type="button"
                className="life-rudra-touch-button"
                aria-label="Start a conversation to explore opportunities"
                onClick={openContactModal}
                whileHover={{
                  y: -5,
                  scale: 1.02,
                  backgroundColor: "var(--brand-gold)",
                  color: "var(--site-bg)",
                  boxShadow:
                    "0 14px 32px rgba(245, 181, 35, 0.2)",
                  transition: {
                    duration: 0.25,
                  },
                }}
                whileTap={{
                  scale: 0.97,
                  y: 0,
                }}
              >
                <motion.span
                  className="life-rudra-button-arrow"
                  whileHover={{
                    x: 6,
                  }}
                >
                  →
                </motion.span>

                <span>Get in touch</span>
              </motion.button>
            </motion.div>
          </motion.div>
        </motion.div>
      </motion.section>

      {/* =====================================================
          CONTACT FORM MODAL
          ===================================================== */}

      <AnimatePresence>
        {isContactModalOpen && (
          <motion.div
            className="about-contact-modal-overlay"
            role="dialog"
            aria-modal="true"
            aria-label="Contact form"
            variants={modalOverlay}
            initial="hidden"
            animate="visible"
            exit="exit"
            onMouseDown={(event) => {
              if (
                event.target === event.currentTarget
              ) {
                closeContactModal();
              }
            }}
          >
            <motion.div
              className="about-contact-modal"
              variants={modalContent}
              initial="hidden"
              animate="visible"
              exit="exit"
              onMouseDown={(event) => {
                event.stopPropagation();
              }}
            >
              {/* CLOSE BUTTON */}

              <motion.button
                type="button"
                className="about-contact-modal-close"
                onClick={closeContactModal}
                aria-label="Close contact form"
                whileHover={{
                  rotate: 90,
                  scale: 1.08,
                  backgroundColor: "#ff6b51",
                }}
                whileTap={{
                  scale: 0.9,
                  rotate: 90,
                }}
              >
                <span />
                <span />
              </motion.button>

              {/* CONTACT FORM */}

              <motion.div
                className="about-contact-modal-content"
                initial={{
                  opacity: 0,
                  y: 15,
                }}
                animate={{
                  opacity: 1,
                  y: 0,
                }}
                transition={{
                  duration: 0.45,
                  delay: 0.15,
                  ease: [0.22, 1, 0.36, 1],
                }}
              >
                <ContactForm />
              </motion.div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
      <SiteFooter/>
    </>
  );
};

export default Page;

